---
- name: Install Postfix
  package: name=postfix state=latest

- name: Enable Postfix
  service: name=postfix state=started enabled=yes

- name: Backup configuration
  shell: >-
    set -euo pipefail;
    cp /etc/postfix/main.cf
    /etc/postfix/main.cf.{{ postfix_backup_multiple |
    ternary("$(date -Iseconds)", "backup") }}
  when: postfix_backup or postfix_backup_multiple

- name: Ensure Last modified header is absent
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '# Last modified:'
    state: absent

- name: Ensure Ansible Managed header in configuration file
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: 'managed by [aA]nsible'
    state: present
    insertbefore: BOF
    line: "# This file is managed by Ansible"

- name: Configure Postfix
  command: "postconf -e \"{{ item.key }}={{ item.value }}\""
  ignore_errors: true
  notify: check restart postfix
  with_dict: "{{ postfix_conf }}"
  changed_when: false
